name: SonarQube Scan

on:
  push:
    branches: main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
     - uses: actions/checkout@v2
      
     - name: Set up Node.js
     - uses: actions/setup-node@v4
       with:
         node-version: '16'
         
     - name: Install dependencies
       run: npm install

     - name: Run SonarQube Scan
       run: |
        npm run build
        npm install -g sonarqube-scanner
        sonar-scanner \-Dsonar.projectKey=${{ github.repository }} \-Dsonar.organization=sonartest \-Dsonar.host.url=https://sonar.ccapps.in/ \-Dsonar.login=${{ secrets.SONAR_TOKEN }}
