name: Publish Docker image

on:
  push:
    branches: ['main']
jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install SonarScanner
      run: |
        # Install SonarScanner
        curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip
        export PATH=dockerimagebuild/.github/workflows/docker-image.yml/sonar-scanner-cli-4.6.2.2472-linux/bin
        
    - name: Install dependencies
      run: npm install

    - name: Run SonarQube analysis with debug
      run: |
        sonar-scanner \
        -D"sonar.projectKey=cicd-sonartest" 
        -D"sonar.sources=." 
        -D"sonar.host.url=https://sonar.ccapps.in" 
        -D"sonar.login=sqp_8184ac69802a6f523fad3ebaf0cc07d0b74f08c9"
        -X
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
