name: Publish Docker image
on: push
jobs:
 sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL : ${{ secrets.SONAR_HOST_URL }}
