bmFtZTogUHVibGlzaCBEb2NrZXIgaW1hZ2UKCm9uOgogIHdvcmtmbG93X2Rp
c3BhdGNoOgoKam9iczoKICBwdXNoX3RvX3JlZ2lzdHJ5OgogICAgbmFtZTog
UHVzaCBEb2NrZXIgaW1hZ2UgdG8gRG9ja2VyIEh1YgogICAgcnVucy1vbjog
dWJ1bnR1LWxhdGVzdAogICAgc3RlcHM6CiAgICAgIC0gbmFtZTogQ2hlY2sg
b3V0IHRoZSByZXBvCiAgICAgICAgdXNlczogYWN0aW9ucy9jaGVja291dEB2
MwogICAgICAtIG5hbWU6IExvZyBpbiB0byBEb2NrZXIgSHViCiAgICAgICAg
dXNlczogZG9ja2VyL2xvZ2luLWFjdGlvbkBmMDU0YThiNTM5YTEwOWY5ZjQx
YzM3MjkzMmYxYWUwNDdlZmYwOGM5CiAgICAgICAgd2l0aDoKICAgICAgICAg
IHVzZXJuYW1lOiAnJwogICAgICAgICAgcGFzc3dvcmQ6ICcnCiAgICAgIAog
ICAgICAtIG5hbWU6IEV4dHJhY3QgbWV0YWRhdGEgKHRhZ3MsIGxhYmVscykg
Zm9yIERvY2tlcgogICAgICAgIGlkOiBtZXRhCiAgICAgICAgdXNlczogZG9j
a2VyL21ldGFkYXRhLWFjdGlvbkA5ODY2OWFlODY1ZWEzY2ZmYmNiYWE4Nzhj
ZjU3YzIwYmJmMWM2YzM4CiAgICAgICAgd2l0aDoKICAgICAgICAgIGltYWdl
czogZ29tYXRoaWthbmFnYXJhai9kb2NrZXJpbWFnZWJ1aWxkCiAgICAgIAog
ICAgICAtIG5hbWU6IEJ1aWxkIGFuZCBwdXNoIERvY2tlciBpbWFnZQogICAg
ICAgIHVzZXM6IGRvY2tlci9idWlsZC1wdXNoLWFjdGlvbkBhZDQ0MDIzYTkz
NzExZTNkZWIzMzc1MDg5ODBiNGI1ZTliY2RjNWRjCiAgICAgICAgd2l0aDoK
ICAgICAgICAgIGNvbnRleHQ6IC4KICAgICAgICAgIHB1c2g6IHRydWUKICAg
ICAgICAgIHRhZ3M6ICR7eyBzdGVwcy5tZXRhLm91dHB1dHMudGFncyB9fQog
ICAgICAgICAgbGFiZWxzOiAke3sgc3RlcHMubWV0YS5vdXRwdXRzLmxhYmVs
cyB9fQo=
